#!/bin/bash
# Thermal Printer Service - Setup & Build Guide

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║     THERMAL PRINTER SERVICE - SETUP & BUILD GUIDE                 ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""

# Step 1: Get dependencies
echo "📦 Step 1: Getting Flutter dependencies..."
echo "Command: flutter pub get"
echo ""

# Step 2: Run build runner
echo "🔨 Step 2: Running build runner for code generation..."
echo "Command: flutter pub run build_runner build --delete-conflicting-outputs"
echo ""
echo "This will generate:"
echo "  ✓ thermal_printer_model.freezed.dart"
echo "  ✓ thermal_printer_model.g.dart"
echo ""

# Step 3: Clean build
echo "🧹 Step 3: Clean build (recommended)..."
echo "Command: flutter clean"
echo ""

# Step 4: Build again
echo "🔨 Step 4: Build app..."
echo "Command: flutter pub get && flutter pub run build_runner build"
echo ""

# Step 5: Run on device
echo "▶️  Step 5: Run on device..."
echo "Command: flutter run"
echo ""

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║                     VERIFICATION CHECKLIST                         ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""

echo "❌ Step 1: Check files exist"
echo "   - lib/features/print/domain/thermal_printer_model.dart"
echo "   - lib/features/print/domain/i_thermal_printer_service.dart"
echo "   - lib/features/print/infrastructure/sunmi_printer_service.dart"
echo "   - lib/features/print/application/thermal_printer_manager.dart"
echo "   - lib/features/print/application/thermal_printer_providers.dart"
echo "   - lib/features/print/presentation/print_invoice_v2.dart"
echo ""

echo "❌ Step 2: Check no compilation errors"
echo "   Run: flutter analyze"
echo ""

echo "❌ Step 3: Test basic functionality"
echo "   Create a test button that calls PrintInvoiceV2().printInvoice()"
echo ""

echo "❌ Step 4: Test with real thermal printer"
echo "   Try printing a test invoice"
echo ""

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║                      GENERATED FILES                              ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""

echo "These files will be auto-generated (do NOT edit):"
echo ""
echo "  📄 lib/features/print/domain/thermal_printer_model.freezed.dart"
echo "    └─ Auto-generated by Freezed"
echo ""
echo "  📄 lib/features/print/domain/thermal_printer_model.g.dart"
echo "    └─ Auto-generated JSON serialization"
echo ""

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║                    TROUBLESHOOTING                                 ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""

echo "⚠️  If you see: 'Target of URI doesn't exist'"
echo "   → Run: flutter pub run build_runner build --delete-conflicting-outputs"
echo ""

echo "⚠️  If you see: 'Undefined class' errors"
echo "   → Run: flutter pub get"
echo "   → Run: flutter pub run build_runner build"
echo ""

echo "⚠️  If nothing works"
echo "   → Run: flutter clean"
echo "   → Run: flutter pub get"
echo "   → Run: flutter pub run build_runner build --delete-conflicting-outputs"
echo ""

echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║                      FINAL COMMANDS                               ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""

echo "Copy and run these commands in order:"
echo ""
echo "1️⃣  flutter clean"
echo ""
echo "2️⃣  flutter pub get"
echo ""
echo "3️⃣  flutter pub run build_runner build --delete-conflicting-outputs"
echo ""
echo "4️⃣  flutter run"
echo ""

echo "═══════════════════════════════════════════════════════════════════════"
echo "✅ Setup complete! Ready to use thermal printer service."
echo "═══════════════════════════════════════════════════════════════════════"
